transform_tolerance: 0.2
obstacle_range: 3.0
raytrace_range: 2.5
inflation_radius: 0.45

observation_sources: base_scan sonar_cloud ir_cloud #vos #inclined_cloud bumper_cloud

base_scan: {sensor_frame: base_laser_link, data_type: LaserScan, topic: scan_filtered, expected_update_rate: 0.3,
  observation_persistence: 0.0, marking: true, clearing: true, min_obstacle_height: -0.1, max_obstacle_height: 0.2}

vos: {sensor_frame: map, data_type: PointCloud, topic: vo_cloud , expected_update_rate: 12.0, 
  observation_persistence: 0.0, marking: true, clearing: false, obstacle_range: 50.0, min_obstacle_height: 0.00, max_obstacle_height: 2.0}

inclined_cloud: {sensor_frame: base_torso_laser_link, data_type: PointCloud2, topic: hokuyo_cloud , expected_update_rate: 1.0,
  observation_persistence: 0.0, marking: true, clearing: true, min_obstacle_height: 0.31, max_obstacle_height: 0.8}

sonar_cloud: {sensor_frame: base_link, data_type: PointCloud2, topic: sonar_cloud, expected_update_rate: 1.0,
  observation_persistence: 0.0, marking: true, clearing: true, raytrace_range: 1.0, obstacle_range: 3.0,
  min_obstacle_height: 0.1, max_obstacle_height: 1.8}

ir_cloud: {sensor_frame: base_link, data_type: PointCloud2, topic: ir_cloud, expected_update_rate: 1.0,
  observation_persistence: 0.0, marking: true, clearing: true, raytrace_range: 2.0, obstacle_range: 1.7,
  min_obstacle_height: 0.2, max_obstacle_height: 1.8}

bumper_cloud: {sensor_frame: base_link, data_type: PointCloud2, topic: bumper_cloud, expected_update_rate: 1.0,
  observation_persistence: 0.0, marking: true, clearing: true, raytrace_range: 1.0, obstacle_range: 0.2,
  min_obstacle_height: 0.1, max_obstacle_height: 0.3}

