# Independent settings for the planner's costmap
global_costmap:
  map_type: costmap

  global_frame: map
  robot_base_frame: base_link

  update_frequency: 1.0
  publish_frequency: 1.0

  static_map: true
  map_topic: map # vo server not starting properly on robot, prevents move_base from starting
  track_unknown_space: true
  unknown_cost_value: 255

  inflation_radius: 0.81
